title = "jimmyff"
description = "Fun loving creative (he/him) ğŸ³ï¸â€ğŸŒˆ"

# The URL the site will be built for
base_url = "https://www.jimmyff.co.uk"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Feeds
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

minify_html = true
default_language = "en"
theme = "zap"

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
  { name = "tags", feed = true },
  { name = "medium", feed = true },
  { name = "series", feed = true },
  { name = "project", feed = true },
  # , render = false
]

[search]
index_format = "fuse_javascript"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false


[extra]

# Put all your custom variables here
# google_analytics_tag_id = 'G-71ZN1D4H6Q'
umami_website_id = '3b272798-439a-429c-b9e8-0e9090275205'
umami_domains = 'www.jimmyff.co.uk,jimmyff.co.uk'
title_suffix = "a creative & geeky personal blog"

keywords = "jimmy, forrester-fellowes, jimmyff, jimmy3ds, yorkshire, leeds, developer"
avatar = "/avatar_2024.webp"
open_graph_image = "/open_graph_image.webp"
favicon = "/favicon.ico"

inline_icons = true
icon_path = "static/icons/"
icons = ["home", "chat", "color-palette", "idea", "gamification", "cube", "wikis", "search", "light", "asleep", "rss"]
image_resizing_disabled = false
image_format = "webp"             # "auto", "jpg", "png", "webp"
image_quality = 80
thumbnail_quality = 70
search_path = "$BASE_URL/search/"

# responsive image shortcode 
# example: {{ image(src="foo.jpeg", alt="some image") }}
images_default_size = 1024
images_sizes = [512, 1024, 2048]

# link_twitter_username = "jimmyff_uk"
# link_mastodon_url = "https://fosstodon.org/@jimmyff"
link_bluesky_url = "https://bsky.app/profile/faehound.games"
link_github_username = "jimmyff"
link_medium_username = "jimmyff"
link_instagram_username = "jimmyff_art"
link_youtube_handle = "jimmyff-uk"

# I have added credit to the zola & the theme on my main homepage under the heading "About this site"
disable_powered_by = false

menu_links = [
  { url = "$BASE_URL/", name = "About", emoji = "ğŸ ", icon = "home.svg" },
  { url = "$BASE_URL/blog/", name = "Blog", emoji = "ğŸ“–", icon = "chat.svg" },
  { url = "$BASE_URL/gallery/", name = "Gallery", emoji = "ğŸ¨", icon = "color-palette.svg" },
  { url = "$BASE_URL/projects/", name = "Projects", emoji = "ğŸ’¡", icon = "idea.svg" },
  { url = "$BASE_URL/games/", name = "Games", emoji = "ğŸ²", icon = "gamification.svg" },
  { url = "$BASE_URL/apps/", name = "Apps", emoji = "ğŸ“±", icon = "cube.svg" },

  { url = "$BASE_URL/guestbook/", name = "Guestbook", emoji = "ğŸŒ", icon = "wikis.svg" },
  #  { url = "$BASE_URL/inktober/", name = "Inktober", emoji = "ğŸ¨" },

  { url = "$BASE_URL/search/", name = "Search", emoji = "ğŸ”", icon = "search.svg" },

]

overflow_menu_links = [
  { url = "$BASE_URL/", name = "Home", emoji = "ğŸ " },
  { url = "$BASE_URL/guestbook/", name = "Guestbook", emoji = "ğŸŒ" },
  { url = "$BASE_URL/apps/", name = "Apps", emoji = "ğŸ“±" },
  { url = "$BASE_URL/inktober/", name = "Inktober", emoji = "ğŸ¨" },
  { url = "https://docs.google.com/forms/d/e/1FAIpQLScIN2i8tudYfvWZO96Ed-_ma011PgZU-CrxRyCXdSA1z9NRjA/viewform", name = "Contact me", emoji = "ğŸ“§" },
  # { url = "$BASE_URL/search/", name = "Search", emoji = "ğŸ”" },

]

emoji_blog = "ğŸ“"
emoji_gallery = "ğŸ¨"
